"""empty message

Revision ID: d4985d9bc30e
Revises: 14d13e2ab05e
Create Date: 2026-09-27 21:31:33.872403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4985d9bc30e'
down_revision = '14d13e2ab05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rescheduled_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_review_id'), ['review_id'], unique=False)
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['review_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_review_id'))
        batch_op.drop_column('review_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('rescheduled_count')

    # ### end Alembic commands ###
